services:
  reverse-proxy:
    image: lmielke/ollama-reverse-proxy:latest
    ports:
      - "80:80"     # User-facing Open Web UI
    environment:
      UI_PORT: 3333
      UI_IP: 172.18.0.1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
