version: "3.8"

services:
  reverse-proxy:
    image: lmielke/ollama-reverse-proxy:latest
    ports:
      - "80:80"
    environment:
      UI_PORT: ${UI_PORT}
      UI_IP: ${UI_IP}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:80 | grep -q '<title>Open WebUI</title>'"]
      interval: 10s
      timeout: 5s
      retries: 3
